# Generated by Django 5.0.4 on 2024-06-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
    ]
