# Generated by Django 5.0.4 on 2024-06-28 12:20

from django.db import migrations


def assign_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()
    for smartphone in smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def assign_category_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    default_category = smartphone_model._meta.get_field('category').default

    smartphones = smartphone_model.objects.all()
    for smartphone in smartphones:
        smartphone.category = default_category

    smartphone_model.objects.bulk_update(smartphones, ['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20240628_1202'),
    ]

    operations = [
        migrations.RunPython(assign_category, assign_category_default)
    ]
