# Generated by Django 5.0.7 on 2024-08-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_fruit_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='Image_url',
            new_name='image_url',
        ),
    ]
