# Generated by Django 5.0.7 on 2024-08-08 15:14

import Fruitipedia.fruits.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_rename_image_url_fruit_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Fruitipedia.fruits.validators.IsOnlyLettersValidator(message='Fruit name should contain only letters!')]),
        ),
    ]
